/* ==========================================================================
   INDICATOR CATALOGUE + THRESHOLD REGISTER  —  data/indicators.js
   --------------------------------------------------------------------------
   code   OIOS code, the key used by data/master.js
   oc     outcome this indicator belongs to
   short  <= 40 characters, used on chart axes and in tables
   thr    threshold as a fraction (0.95 = 95%), or null for TBC
   dir    1 = higher is better, -1 = reduction indicator
   ========================================================================== */
window.WVI_INDICATORS = [
  {code:"OIOS 1", oc:"Goal", short:"Child well-being — overall", thr:null, dir:1,
   ind:"Proportion of children reporting an increased level of overall well-being",
   numdef:"Children aged 12–18 whose composite CWB score improved against baseline", dendef:"All children aged 12–18 surveyed",
   src:"CWB survey · AIM+ FY26", thrsrc:"Global CWB Aspiration"},
  {code:"OIOS 2", oc:"Goal", short:"Life satisfaction (12–18)", thr:0.62, dir:1,
   ind:"Proportion of children aged 12–18 reporting life satisfaction at or above the national median",
   numdef:"Children scoring ≥ national median on the life-satisfaction scale", dendef:"All children aged 12–18 surveyed",
   src:"CWB survey · AIM+ FY26", thrsrc:"National Strategy FY26–30"},
  {code:"OIOS 96", oc:"OC 1", short:"Basic drinking water", thr:0.95, dir:1,
   ind:"Proportion of households using at least basic drinking water services",
   numdef:"Households with an improved source within 30 minutes round trip", dendef:"All households surveyed",
   src:"JMP ladder · household survey", thrsrc:"SDG 6.1 / JMP basic service"},
  {code:"OIOS 97", oc:"OC 1", short:"Basic sanitation", thr:1, dir:1,
   ind:"Proportion of households using at least basic sanitation services",
   numdef:"Households with an improved, not-shared facility", dendef:"All households surveyed",
   src:"JMP ladder · household survey", thrsrc:"National ODF target"},
  {code:"OIOS 98", oc:"OC 1", short:"Handwashing facility with soap", thr:0.9, dir:1,
   ind:"Proportion of households with a basic handwashing facility with soap and water",
   numdef:"Households with a fixed or mobile facility, soap and water present", dendef:"All households surveyed",
   src:"JMP ladder · household survey", thrsrc:"SDG 6.2 / JMP basic hygiene"},
  {code:"OIOS 12", oc:"OC 1", short:"Stunting, under-5", thr:0.14, dir:-1,
   ind:"Prevalence of stunting among children under five years",
   numdef:"Children under 5 with height-for-age below −2 SD", dendef:"All children under 5 measured",
   src:"Anthropometry · SSGI reference", thrsrc:"RPJMN 2030 target"},
  {code:"OIOS 14", oc:"OC 1", short:"Minimum acceptable diet", thr:0.7, dir:1,
   ind:"Proportion of children 6–23 months receiving a minimum acceptable diet",
   numdef:"Children 6–23 months meeting MDD and MMF", dendef:"All children 6–23 months surveyed",
   src:"IYCF module · household survey", thrsrc:"WHO IYCF benchmark"},
  {code:"OIOS 15", oc:"OC 1", short:"Exclusive breastfeeding", thr:0.8, dir:1,
   ind:"Proportion of infants under 6 months exclusively breastfed",
   numdef:"Infants under 6 months fed only breast milk in the last 24 hours", dendef:"All infants under 6 months surveyed",
   src:"IYCF module · household survey", thrsrc:"WHA global target"},
  {code:"OIOS 16", oc:"OC 1", short:"Antenatal care, 4+ visits", thr:0.85, dir:1,
   ind:"Proportion of women who attended four or more antenatal care visits",
   numdef:"Women with a live birth in the last 2 years reporting 4+ ANC visits", dendef:"All women with a live birth in the last 2 years",
   src:"Household survey · MCH card", thrsrc:"National SPM health standard"},
  {code:"OIOS 31", oc:"OC 2", short:"Reading with comprehension", thr:0.8, dir:1,
   ind:"Proportion of children aged 6–11 who can read with comprehension",
   numdef:"Children answering ≥80% of comprehension items correctly", dendef:"All children aged 6–11 assessed",
   src:"Functional literacy assessment", thrsrc:"Unlock Literacy benchmark"},
  {code:"OIOS 32", oc:"OC 2", short:"Reading at grade level", thr:0.75, dir:1,
   ind:"Proportion of children reading at or above grade level",
   numdef:"Children at or above the grade-level fluency band", dendef:"All children assessed",
   src:"Functional literacy assessment", thrsrc:"Unlock Literacy benchmark"},
  {code:"OIOS 33", oc:"OC 2", short:"Caregiver engagement in learning", thr:0.7, dir:1,
   ind:"Proportion of caregivers engaged in their child's learning at home",
   numdef:"Caregivers reporting 3+ qualifying support activities in the last week", dendef:"All caregivers of assessed children",
   src:"Caregiver survey", thrsrc:"Unlock Literacy benchmark"},
  {code:"OIOS 34", oc:"OC 2", short:"On-time primary completion", thr:0.9, dir:1,
   ind:"Proportion of children completing primary education on time",
   numdef:"Children completing grade 6 within one year of the expected age", dendef:"All children of primary-completion age",
   src:"School records + household survey", thrsrc:"National SPM education standard"},
  {code:"OIOS 35", oc:"OC 2", short:"Foundational numeracy", thr:null, dir:1,
   ind:"Proportion of children demonstrating foundational numeracy",
   numdef:"Children meeting the foundational numeracy band", dendef:"All children aged 7–11 assessed",
   src:"Numeracy assessment", thrsrc:"Threshold under review by sector"},
  {code:"OIOS 6", oc:"OC 3", short:"Positive relations — caregivers", thr:0.843, dir:1,
   ind:"Proportion of children reporting positive relationships with their caregivers",
   numdef:"Children scoring ≥ cut-off on the caregiver-relations scale", dendef:"All children aged 12–18 surveyed",
   src:"CWB survey · AIM+ FY26", thrsrc:"Global CWB Aspiration"},
  {code:"OIOS 7", oc:"OC 3", short:"Positive relations — peers", thr:0.772, dir:1,
   ind:"Proportion of children reporting positive relationships with their peers",
   numdef:"Children scoring ≥ cut-off on the peer-relations scale", dendef:"All children aged 12–18 surveyed",
   src:"CWB survey · AIM+ FY26", thrsrc:"Global CWB Aspiration"},
  {code:"OIOS 10", oc:"OC 3", short:"High self-efficacy (12–18)", thr:0.34, dir:1,
   ind:"Proportion of children aged 12–18 demonstrating high self-efficacy",
   numdef:"Children scoring in the high band of the self-efficacy scale", dendef:"All children aged 12–18 surveyed",
   src:"CWB survey · AIM+ FY26", thrsrc:"IMPACT+ model benchmark"},
  {code:"OIOS 22", oc:"OC 3", short:"Violent discipline — caregiver", thr:0.1, dir:-1,
   ind:"Proportion of children reporting violent discipline by a caregiver in the past month",
   numdef:"Children reporting any physical or psychological violent discipline", dendef:"All children aged 12–18 surveyed",
   src:"CWB survey · AIM+ FY26", thrsrc:"PROTECT model benchmark"},
  {code:"OIOS 23", oc:"OC 3", short:"Peer violence", thr:0.12, dir:-1,
   ind:"Proportion of children reporting peer violence in the past month",
   numdef:"Children reporting any peer physical or verbal violence", dendef:"All children aged 12–18 surveyed",
   src:"CWB survey · AIM+ FY26", thrsrc:"PROTECT model benchmark"},
  {code:"OIOS 27", oc:"OC 3", short:"Married before 18 (20–24)", thr:0.1, dir:-1,
   ind:"Proportion of women aged 20–24 married or in union before age 18",
   numdef:"Women 20–24 first married or in union before their 18th birthday", dendef:"All women aged 20–24 surveyed",
   src:"Household survey", thrsrc:"National child-marriage strategy"},
  {code:"OIOS 28", oc:"OC 3", short:"Birth registration, under-5", thr:0.95, dir:1,
   ind:"Proportion of children under five whose birth is registered",
   numdef:"Children under 5 with a birth certificate seen or reported", dendef:"All children under 5 surveyed",
   src:"Household survey · Dukcapil", thrsrc:"National civil-registration target"},
  {code:"OIOS 61", oc:"OC 4", short:"Household resilience capacity", thr:0.6, dir:1,
   ind:"Proportion of households demonstrating improved resilience capacity",
   numdef:"Households scoring ≥ cut-off on the resilience index", dendef:"All targeted households surveyed",
   src:"Resilience module", thrsrc:"National Strategy FY26–30"},
  {code:"OIOS 62", oc:"OC 4", short:"Household food security", thr:0.75, dir:1,
   ind:"Proportion of households that are food secure",
   numdef:"Households classified food secure on HFIAS", dendef:"All targeted households surveyed",
   src:"HFIAS module", thrsrc:"FAO HFIAS classification"},
  {code:"OIOS 63", oc:"OC 4", short:"Savings group participation", thr:0.55, dir:1,
   ind:"Proportion of targeted households participating in a savings group",
   numdef:"Households with an active member in a savings group", dendef:"All targeted households",
   src:"Group registers", thrsrc:"S4T model benchmark"},
  {code:"OIOS 64", oc:"OC 4", short:"Income diversification", thr:null, dir:1,
   ind:"Proportion of households with two or more income sources",
   numdef:"Households reporting 2+ distinct income sources", dendef:"All targeted households surveyed",
   src:"Livelihood module", thrsrc:"Threshold under review by sector"},
  {code:"OIOS 71", oc:"OC 4", short:"Faith leader engagement", thr:0.65, dir:1,
   ind:"Proportion of faith leaders actively engaged in child well-being action",
   numdef:"Faith leaders with a documented CWB action in the last 6 months", dendef:"All faith leaders mapped in the AP",
   src:"Partner records", thrsrc:"Channels of Hope benchmark"}
];
